import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, CheckCircle2, ShieldCheck } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { apiFetch } from '@/lib/api'

type Portal = { workspace: { name: string; kind: string; industryCode: string; currency: string }; safetyAcknowledged: boolean; safetyRequirements: string[]; botReview: { status: string; checks: string[] }; monitoring: { status: string; monitoredSignals: string[] }; expiresAt: string }

function ClientPortalPage() {
  const { token = '' } = useParams()
  const queryClient = useQueryClient()
  const [accepted, setAccepted] = useState(false)
  const portal = useQuery({ queryKey: ['client-portal', token], queryFn: () => apiFetch<Portal>(`/api/client-portal/${token}`), enabled: token.length > 0 })
  const acknowledge = useMutation({ mutationFn: () => apiFetch(`/api/client-portal/${token}/acknowledge`, { method: 'POST', body: JSON.stringify({ acknowledged: true }) }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['client-portal', token] }) })
  if (!portal.data) return <div className="min-h-dvh bg-[#f7f8f6] px-6 py-16 text-center text-sm text-[#74827e]">Loading secure client portal...</div>
  const data = portal.data
  return <div className="min-h-dvh bg-[#f7f8f6] px-4 py-10 text-[#1d2c2a] sm:px-8"><main className="mx-auto max-w-3xl"><header className="mb-8"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#287b5b]"><span className="size-2 rounded-full bg-[#287b5b]" /> Dea Foundations client portal</div><h1 className="mt-5 text-3xl font-semibold tracking-[-0.04em]">{data.workspace.name}</h1><p className="mt-2 text-sm capitalize text-[#74827e]">{data.workspace.kind} · {data.workspace.industryCode.replaceAll('-', ' ')} · {data.workspace.currency}</p></header><div className="grid gap-5 sm:grid-cols-2"><section className="rounded-2xl border border-[#e4e9e5] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e7f5ed] text-[#287b5b]"><ShieldCheck size={19} /></span><div><h2 className="font-semibold">Safety requirements</h2><p className="text-xs text-[#8b9793]">Required before using the workspace.</p></div></div><div className="mt-5 space-y-3">{data.safetyRequirements.map((requirement) => <label key={requirement} className="flex gap-3 text-sm leading-5 text-[#53645f]"><input type="checkbox" checked={data.safetyAcknowledged || accepted} onChange={(event) => setAccepted(event.target.checked)} className="mt-1 accent-[#287b5b]" />{requirement}</label>)}</div><button type="button" disabled={!accepted || data.safetyAcknowledged || acknowledge.isPending} onClick={() => acknowledge.mutate()} className="mt-6 rounded-lg bg-[#287b5b] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{data.safetyAcknowledged ? 'Requirements acknowledged' : 'Acknowledge requirements'}</button></section><section className="space-y-5"><div className="rounded-2xl border border-[#e4e9e5] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Activity className="text-[#287b5b]" size={20} /><h2 className="font-semibold">Monitoring status</h2></div><p className="mt-4 flex items-center gap-2 text-sm text-[#287b5b]"><CheckCircle2 size={16} /> {data.monitoring.status}</p><p className="mt-3 text-xs leading-5 text-[#8b9793]">Signals monitored: {data.monitoring.monitoredSignals.join(', ')}.</p></div><div className="rounded-2xl border border-[#e4e9e5] bg-white p-6 shadow-sm"><h2 className="font-semibold">Bot review</h2><p className="mt-3 text-sm text-[#287b5b]">{data.botReview.status}</p><ul className="mt-3 space-y-2 text-xs text-[#8b9793]">{data.botReview.checks.map((check) => <li key={check} className="flex gap-2"><CheckCircle2 size={14} className="text-[#287b5b]" />{check}</li>)}</ul></div></section></div><p className="mt-6 text-center text-xs text-[#9aa59f]">This private link expires {new Date(data.expiresAt).toLocaleDateString()}.</p></main></div>
}

export default ClientPortalPage